backend:
  name: git-gateway
  repo: ppiron/clean-blog
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

publish_mode: editorial_workflow

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

display_url: http://localhost:8080

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/experience
    identifier_field: name
    label: "Posts" # Used in the UI
    folder: "src/posts"
    create: true # Allow users to create new documents in this collection
    slug: "name.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "sub", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
